###  localhost requests

@localhostName = http://localhost:8080

// LOGIN REQUESTS
GET {{localhostName}}/login

// CUSTOMERS REQUESTS

### returns a json object with all customers data.
GET {{localhostName}}/customers

### returns a json object with a specific customer.
GET {{localhostName}}/customers/667f14069f26d41793a39bc1

### creates a new customer.
POST {{localhostName}}/customers HTTP/1.1
content-type: application/json

{
    "firstName":"Buster",
    "lastName":"Douglas",
    "email":"buster.douglas@test.com",
    "favoriteColor":"gray",
    "birthday":"11/30/1970",
    "phone":"+1 803 5555-9999",
    "address": "451 5th Ave",
    "city": "Los Angeles",
    "state": "CA",
    "zip": "12345"
}

### updates an existing customer.
PUT {{localhostName}}/customers/6682df511dd904faf9e78e94  HTTP/1.1
content-type: application/json

{
    "firstName":"Buster",
    "lastName":"Douglas",
    "email":"buster.douglas@test.com",
    "favoriteColor":"gray",
    "birthday":"11/30/1970",
    "phone":"+1 803 5555-0000",
    "address": "451 5th Ave",
    "city": "Los Angeles",
    "state": "CA",
    "zip": "12345"
}

### removes an existing customer
DELETE {{localhostName}}/customers/6682df511dd904faf9e78e94 HTTP/1.1


// PRODUCTS REQUESTS

### returns a json object with all products data.
GET {{localhostName}}/products

### returns a json object with a specific customer.
GET {{localhostName}}/products/667f20fc906320429e341a8f

### creates a new product.
POST {{localhostName}}/products HTTP/1.1
content-type: application/json

{
  "productName": "New Product for Test",
  "description": "This product is used to test create, put and delete requests.",
  "price": 745.69,
  "category": "dog vet food",
  "sku": "600999"
}

### updates an existing product.
PUT {{localhostName}}/products/6682e0dc1dd904faf9e78e95 HTTP/1.1
content-type: application/json

{
  "productName": "New Product for Test",
  "description": "This product is used to test create, put and delete requests.",
  "price": 745.69,
  "category": "fake products",
  "sku": "600999"
}

### removes an existing product
DELETE {{localhostName}}/products/6682e0dc1dd904faf9e78e95 HTTP/1.1

// SELLERS REQUESTS

### returns a json object with all sellers data.
GET {{localhostName}}/sellers

### returns a json object with a specific seller.
GET {{localhostName}}/sellers/667f14069f26d41793a39bc1

### creates a new seller.
POST {{localhostName}}/sellers HTTP/1.1
content-type: application/json

{
  "firstName": "John",
  "lastName": "Kennedy",
  "email": "joe.ken@test.com",
  "phone": "+1 803 5555-9999",
  "fixedSalary": 5000,
  "commissionRate": 0.05
}

### updates an existing customer.
PUT {{localhostName}}/sellers/6682df511dd904faf9e78e94  HTTP/1.1
content-type: application/json

{
    "firstName":"Buster",
    "lastName":"Douglas",
    "email":"buster.douglas@test.com",
    "favoriteColor":"gray",
    "birthday":"11/30/1970",
    "phone":"+1 803 5555-0000",
    "address": "451 5th Ave",
    "city": "Los Angeles",
    "state": "CA",
    "zip": "12345"
}

### removes an existing customer
DELETE {{localhostName}}/sellers/6682df511dd904faf9e78e94 HTTP/1.1


// API DOCUMENTATION

### opens the API documentation 
GET {{localhostName}}/api-docs

// **************************************************************************************************
###  Render requests

@publishedHostName = https://cse-341-customers.onrender.com

// CUSTOMERS REQUESTS

### returns a json object with all customers data.
GET {{publishedHostName}}/customers

### returns a json object with a specific customer.
GET {{publishedHostName}}/customers/667ffd0352fbc34c2945854

### creates a new customer.
POST {{publishedHostName}}/customers HTTP/1.1
content-type: application/json

{
    "firstName":"Buster",
    "lastName":"Douglas",
    "email":"buster.douglas@test.com",
    "favoriteColor":"gray",
    "birthday":"11/30/1970",
    "phone":"+1 803 5555-9999",
    "address": "451 5th Ave",
    "city": "Los Angeles",
    "state": "CA",
    "zip": "12345"
}

### updates an existing customer.
PUT {{publishedHostName}}/customers/668304114dc7d0d9108420e4  HTTP/1.1
content-type: application/json

{
    "firstName":"Buster",
    "lastName":"Douglas",
    "email":"buster.douglas@test.com",
    "favoriteColor":"gray",
    "birthday":"11/30/1970",
    "phone":"+1 803 5555-0000",
    "address": "451 5th Ave",
    "city": "Los Angeles",
    "state": "CA",
    "zip": "12345"
}

### removes an existing customer
DELETE {{publishedHostName}}/customers/668304114dc7d0d9108420e4 HTTP/1.1

### returns a json object with all products data.
GET {{publishedHostName}}/products

### returns a json object with a specific product.
GET {{publishedHostName}}/products/667f1f60906320429e341a8c

// PRODUCTS REQUESTS

### returns a json object with all products data.
GET {{publishedHostName}}/products

### returns a json object with a specific customer.
GET {{publishedHostName}}/products/667f20fc906320429e341a8f

### creates a new product.
POST {{publishedHostName}}/products HTTP/1.1
content-type: application/json

{
  "productName": "New Product for Test",
  "description": "This product is used to test create, put and delete requests.",
  "price": 745.69,
  "category": "dog vet food",
  "sku": "600999"
}

### updates an existing product.
PUT {{publishedHostName}}/products/668304e84dc7d0d9108420e5 HTTP/1.1
content-type: application/json

{
  "productName": "New Product for Test",
  "description": "This product is used to test create, put and delete requests.",
  "price": 745.69,
  "category": "fake products",
  "sku": "600999"
}

### removes an existing product
DELETE {{publishedHostName}}/products/668304e84dc7d0d9108420e5 HTTP/1.1

// API DOCUMENTATION

### opens the API documentation 
GET {{publishedHostName}}/api-docs
